[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql://finance_db_arbk_user:VvS0XGab2UWXUiVgrt7843V14vvwcdXt@dpg-d77r27v5r7bs739i94k0-a.oregon-postgres.render.com/finance_db_arbk

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
